# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ppXAFS_dev.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1429, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1381, 671))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(1110, 550, 251, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(150, 500, 350, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.dsB_pre_end = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsB_pre_end.setGeometry(QtCore.QRect(240, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dsB_pre_end.setFont(font)
        self.dsB_pre_end.setMaximum(30000.0)
        self.dsB_pre_end.setObjectName("dsB_pre_end")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(195, 35, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 34, 44, 16))
        self.label.setObjectName("label")
        self.dsB_pre_start = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsB_pre_start.setGeometry(QtCore.QRect(70, 30, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dsB_pre_start.setFont(font)
        self.dsB_pre_start.setMaximum(30000.0)
        self.dsB_pre_start.setObjectName("dsB_pre_start")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(520, 520, 91, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(520, 580, 91, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 570, 350, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.dsB_post_end = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsB_post_end.setGeometry(QtCore.QRect(240, 30, 101, 25))
        self.dsB_post_end.setMaximum(30000.0)
        self.dsB_post_end.setObjectName("dsB_post_end")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(195, 35, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 34, 41, 16))
        self.label_4.setObjectName("label_4")
        self.dsB_post_start = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsB_post_start.setGeometry(QtCore.QRect(70, 30, 111, 25))
        self.dsB_post_start.setMaximum(30000.0)
        self.dsB_post_start.setObjectName("dsB_post_start")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(1250, 11, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(1110, 50, 251, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(20, 60, 611, 401))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.tab_3)
        self.widget_2.setGeometry(QtCore.QRect(640, 20, 451, 601))
        self.widget_2.setObjectName("widget_2")
        self.combo_fynctype = QtWidgets.QComboBox(self.tab_3)
        self.combo_fynctype.setGeometry(QtCore.QRect(350, 475, 131, 27))
        self.combo_fynctype.setObjectName("combo_fynctype")
        self.combo_fynctype.addItem("")
        self.combo_fynctype.addItem("")
        self.combo_fynctype.addItem("")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(300, 480, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(490, 478, 111, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lE_posneg = QtWidgets.QLineEdit(self.tab_3)
        self.lE_posneg.setGeometry(QtCore.QRect(105, 17, 113, 31))
        self.lE_posneg.setObjectName("lE_posneg")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 16, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 50, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.rB_kpower0 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rB_kpower0.setGeometry(QtCore.QRect(10, 35, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.rB_kpower0.setFont(font)
        self.rB_kpower0.setObjectName("rB_kpower0")
        self.rB_kpower1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rB_kpower1.setGeometry(QtCore.QRect(60, 35, 41, 20))
        self.rB_kpower1.setObjectName("rB_kpower1")
        self.rB_kpower2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rB_kpower2.setGeometry(QtCore.QRect(110, 35, 41, 20))
        self.rB_kpower2.setObjectName("rB_kpower2")
        self.rB_kpower3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rB_kpower3.setGeometry(QtCore.QRect(160, 35, 41, 20))
        self.rB_kpower3.setObjectName("rB_kpower3")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setGeometry(QtCore.QRect(20, 140, 951, 451))
        self.widget_4.setObjectName("widget_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(1010, 60, 351, 551))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 349, 549))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.pB_openchi = QtWidgets.QPushButton(self.tab_2)
        self.pB_openchi.setGeometry(QtCore.QRect(1260, 11, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pB_openchi.setFont(font)
        self.pB_openchi.setObjectName("pB_openchi")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(250, 20, 541, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(380, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(120, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comBox_Pos = QtWidgets.QComboBox(self.frame)
        self.comBox_Pos.setGeometry(QtCore.QRect(10, 60, 251, 26))
        self.comBox_Pos.setObjectName("comBox_Pos")
        self.comBox_Neg = QtWidgets.QComboBox(self.frame)
        self.comBox_Neg.setGeometry(QtCore.QRect(280, 60, 251, 26))
        self.comBox_Neg.setObjectName("comBox_Neg")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pB_addchi = QtWidgets.QPushButton(self.tab_2)
        self.pB_addchi.setGeometry(QtCore.QRect(1010, 11, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pB_addchi.setFont(font)
        self.pB_addchi.setObjectName("pB_addchi")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 550, 241, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 70, 241, 471))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 239, 469))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setGeometry(QtCore.QRect(280, 20, 1081, 611))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 20, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1429, 22))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAuto_load = QtWidgets.QAction(MainWindow)
        self.actionAuto_load.setCheckable(True)
        self.actionAuto_load.setObjectName("actionAuto_load")
        self.actionBoost = QtWidgets.QAction(MainWindow)
        self.actionBoost.setCheckable(True)
        self.actionBoost.setObjectName("actionBoost")
        self.menuOption.addAction(self.actionAuto_load)
        self.menuOption.addAction(self.actionBoost)
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.combo_fynctype.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "Select All"))
        self.groupBox.setTitle(_translate("MainWindow", "Lower"))
        self.label_2.setText(_translate("MainWindow", "End:"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.pushButton_13.setText(_translate("MainWindow", "Save"))
        self.pushButton_11.setText(_translate("MainWindow", "replot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Upper"))
        self.label_3.setText(_translate("MainWindow", "End:"))
        self.label_4.setText(_translate("MainWindow", "Start:"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        self.combo_fynctype.setItemText(0, _translate("MainWindow", "average"))
        self.combo_fynctype.setItemText(1, _translate("MainWindow", "linear"))
        self.combo_fynctype.setItemText(2, _translate("MainWindow", "victoreen"))
        self.label_7.setText(_translate("MainWindow", "Method"))
        self.checkBox_2.setText(_translate("MainWindow", "show raw&bk"))
        self.lE_posneg.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Write Ipos and Ineg row name</span></p><p><span style=\" font-size:12pt;\">pos: Ipos/I1/I3</span></p><p><span style=\" font-size:12pt;\">neg: Ineg/I2/I4</span></p></body></html>"))
        self.lE_posneg.setText(_translate("MainWindow", "Ipos, Ineg"))
        self.label_8.setText(_translate("MainWindow", "[Ipos, Ineg]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "XANES"))
        self.groupBox_3.setTitle(_translate("MainWindow", "k weight(x)"))
        self.rB_kpower0.setText(_translate("MainWindow", "0"))
        self.rB_kpower1.setText(_translate("MainWindow", "1"))
        self.rB_kpower2.setText(_translate("MainWindow", "2"))
        self.rB_kpower3.setText(_translate("MainWindow", "3"))
        self.pB_openchi.setText(_translate("MainWindow", "Open"))
        self.label_6.setText(_translate("MainWindow", "Neg."))
        self.label_5.setText(_translate("MainWindow", "Pos."))
        self.checkBox.setText(_translate("MainWindow", "plot diff chi(k)"))
        self.pB_addchi.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "EXAFS"))
        self.pushButton_7.setText(_translate("MainWindow", "Open"))
        self.pushButton_9.setText(_translate("MainWindow", "Save Sum"))
        self.pushButton_2.setText(_translate("MainWindow", "Select/Release All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "TimeScan"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.actionAuto_load.setText(_translate("MainWindow", "auto load"))
        self.actionBoost.setText(_translate("MainWindow", "boost"))

